apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: tp-kubernetes-postgres
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/tp-kubernetes-postgres: "true"
  podSelector:
    matchLabels:
      io.kompose.network/tp-kubernetes-postgres: "true"
