apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/tp-kubernetes-postgres: "true"
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: changeme
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: postgres-container
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgres
              name: postgres-claim0
            - mountPath: /var/log/postgres
              name: postgres-claim1
      restartPolicy: Always
      volumes:
        - name: postgres-claim0
          hostPath:
            path: /run/desktop/mnt/host/c/source/repositories/kubernetes/postgres_data/data
            type: DirectoryOrCreate
        - name: postgres-claim1
          hostPath:
            path: /run/desktop/mnt/host/c/source/repositories/kubernetes/postgres_data/log
            type: DirectoryOrCreate
